# Generated by Django 4.2.7 on 2025-04-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Poor'), (4, 'Below Average'), (5, 'Average'), (6, 'Above Average'), (7, 'Good'), (8, 'Very Good'), (9, 'Great'), (10, 'Excellent')])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
