# Generated by Django 4.2.7 on 2025-05-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge_image',
            field=models.ImageField(blank=True, null=True, upload_to='achievement_badges/'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quest_images/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reward_images/'),
        ),
    ]
